import pandas as pd 
import psycopg2


conn = psycopg2.connect(
    user = 'postgres',
    password = 'gagll1i1', 
    host = 'localhost', 
    port = '5432', 
    database = 'yaencontre'
)
conn.autocommit = True

import_db = 'SELECT * FROM information'
df = pd.read_sql_query(import_db, conn)



cities_to_province = {
    'madrid': 'Madrid',
    'coruna-a': 'A Coruña',
    'barcelona': 'Barcelona',
    'valencia': 'Valencia',
    'sevilla': 'Sevilla',
    'malaga': 'Málaga',
    'murcia': 'Murcia',
    'palma-de-mallorca': 'Islas Baleares',
    'palmas-de-gran-canaria-las': 'Las Palmas',
    'bilbao': 'Vizcaya',
    'cordoba': 'Córdoba',
    'valladolid': 'Valladolid',
    'vigo': 'Pontevedra',
    'gijon': 'Asturias',
    'hospitalet-de-llobregat-l': 'Barcelona',
    'vitoria-gasteiz': 'Álava',
    'elche-elx': 'Alicante',
    'granada': 'Granada',
    'terrassa': 'Barcelona',
    'badalona': 'Barcelona',
    'cartagena': 'Murcia',
    'sabadell': 'Barcelona',
    'oviedo': 'Asturias',
    'jerez-de-la-frontera': 'Cádiz',
    'mostoles': 'Madrid',
    'pamplona-iruna': 'Navarra',
    'santa-cruz-de-tenerife': 'Santa Cruz de Tenerife',
    'almeria': 'Almería',
    'alcala-de-henares': 'Madrid',
    'fuenlabrada': 'Madrid',
    'san-sebastian-donostia': 'Guipúzcoa',
    'san-sebastian-de-los-reyes': 'Madrid',
    'leganes': 'Madrid',
    'getafe': 'Madrid',
    'burgos': 'Burgos',
    'albacete': 'Albacete',
    'castellon-de-la-plana-castello-de-la-plana': 'Castellón',
    'santander': 'Cantabria',
    'alcorcon': 'Madrid',
    'san-cristobal-de-la-laguna': 'Santa Cruz de Tenerife',
    'marbella': 'Málaga',
    'badajoz': 'Badajoz',
    'logrono': 'La Rioja',
    'salamanca': 'Salamanca',
    'huelva': 'Huelva',
    'lleida': 'Lleida',
    'dos-hermanas': 'Sevilla',
    'tarragona': 'Tarragona',
    'torrejon-de-ardoz': 'Madrid',
    'parla': 'Madrid',
    'mataro': 'Barcelona',
    'algeciras': 'Cádiz',
    'leon': 'León',
    'tres-cantos': 'Madrid',
    'guadalajara': 'Guadalajara',
    'ciudad-real': 'Ciudad Real',
    'zaragoza': 'Zaragoza',
    'aranjuez': 'Madrid',
    'zamora': 'Zamora',
    'merida': 'Badajoz',
    'alcoy': 'Alicante',
    'motril': 'Granada',
    'girona': 'Girona',
    'alcobendas': 'Madrid',
    'cadiz': 'Cádiz',
    'jaen': 'Jaén',
    'reus': 'Tarragona',
    'ourense': 'Ourense',
    'telde': 'Las Palmas',
    'barakaldo': 'Vizcaya',
    'santiago-de-compostela': 'A Coruña',
    'lugo': 'Lugo',
    'lorca': 'Murcia',
    'rivas-vaciamadrid': 'Madrid',
    'sant-cugat-del-valles': 'Barcelona',
    'rozas-de-madrid-las': 'Madrid',
    'caceres': 'Cáceres',
    'toledo': 'Toledo',
    'melilla': 'Melilla',
    'torrent': 'Valencia',
    'coslada': 'Madrid',
    'ceuta': 'Ceuta',
    'pontevedra': 'Pontevedra',
    'arona': 'Santa Cruz de Tenerife',
    'fuengirola': 'Málaga',
    'orihuela': 'Alicante',
    'rubi': 'Barcelona',
    'valdemoro': 'Madrid',
    'manresa': 'Barcelona',
    'getxo': 'Vizcaya',
    'palencia': 'Palencia',
    'gandia': 'Valencia',
    'aviles': 'Asturias',
    'ibiza': 'Islas Baleares',
    'segovia': 'Segovia',
    'torrelavega': 'Cantabria',
    'villareal': 'Castellón',
    'utrera': 'Sevilla',
    'siero': 'Asturias',
    'elda': 'Alicante',
    'calviá': 'Islas Baleares',
    'huesca': 'Huesca',
    'cuenca': 'Cuenca',
    'pinto': 'Madrid',
    'linares': 'Jaén',
    'avila': 'Ávila',
    'granollers': 'Barcelona',
    'irun': 'Guipúzcoa',
    'ponferrada': 'León',
    'ferrol': 'A Coruña',
    'arrecife': 'Las Palmas',
    'viladecans': 'Barcelona',
    'castelldefels': 'Barcelona',
    'sagunto': 'Valencia',
    'torremolinos': 'Málaga',
    'benidorm': 'Alicante',
    'paterna': 'Valencia',
    'majadahonda': 'Madrid',
    'benalmadena': 'Málaga',
    'estepona': 'Málaga',
    'torrevieja': 'Alicante',
    'velez-malaga': 'Málaga',
    'mijas': 'Málaga',
    'san-fernando': 'Cádiz',
    'ejido-el': 'Almería',
    'santa-coloma-de-gramanet': 'Barcelona',
    'roquetas-de-mar': 'Almería',
    'puerto-de-santa-maria-el': 'Cádiz',
    'chiclana-de-la-frontera': 'Cádiz',
    'molina-de-segura': 'Murcia',
    'sant-boi-de-llobregat': 'Barcelona',
    'talavera-de-la-reina': 'Toledo',
    'alcala-de-guadaira': 'Sevilla',
    'santa-lucia-de-tirajana': 'Las Palmas',
    'sanlucar-de-barrameda': 'Cádiz',
    'prat-de-llobregat-el': 'Barcelona',
    'colmenar-viejo': 'Madrid',
    'arganda-del-rey': 'Madrid',
    'boadilla-del-monte': 'Madrid',
    'collado-villalba': 'Madrid',
    'mollet-del-valles': 'Barcelona',
    'rincon-de-la-victoria': 'Málaga',
    'granadilla-de-abona': 'Santa Cruz de Tenerife',
    'san-bartolome-de-tirajana': 'Las Palmas',
    'linea-de-la-concepcion-la': 'Cádiz',
    'san-vicente-del-raspeig': 'Alicante',
    'sardanola-del-valles': 'Barcelona'
}

provinces_to_ccaa = {
    'A Coruña': 'Galicia',
    'Álava': 'País Vasco',
    'Albacete': 'Castilla-La Mancha',
    'Alicante': 'Comunidad Valenciana',
    'Almería': 'Andalucía',
    'Asturias': 'Principado de Asturias',
    'Ávila': 'Castilla y León',
    'Badajoz': 'Extremadura',
    'Barcelona': 'Cataluña',
    'Burgos': 'Castilla y León',
    'Cáceres': 'Extremadura',
    'Cádiz': 'Andalucía',
    'Cantabria': 'Cantabria',
    'Castellón': 'Comunidad Valenciana',
    'Ciudad Real': 'Castilla-La Mancha',
    'Córdoba': 'Andalucía',
    'Cuenca': 'Castilla-La Mancha',
    'Gerona': 'Cataluña',
    'Granada': 'Andalucía',
    'Guadalajara': 'Castilla-La Mancha',
    'Guipúzcoa': 'País Vasco',
    'Huelva': 'Andalucía',
    'Huesca': 'Aragón',
    'Islas Baleares': 'Islas Baleares',
    'Jaén': 'Andalucía',
    'La Coruña': 'Galicia',
    'La Rioja': 'La Rioja',
    'Las Palmas': 'Islas Canarias',
    'León': 'Castilla y León',
    'Lérida': 'Cataluña',
    'Lugo': 'Galicia',
    'Madrid': 'Comunidad de Madrid',
    'Málaga': 'Andalucía',
    'Murcia': 'Región de Murcia',
    'Navarra': 'Comunidad Foral de Navarra',
    'Orense': 'Galicia',
    'Palencia': 'Castilla y León',
    'Pontevedra': 'Galicia',
    'Salamanca': 'Castilla y León',
    'Santa Cruz de Tenerife': 'Islas Canarias',
    'Segovia': 'Castilla y León',
    'Sevilla': 'Andalucía',
    'Soria': 'Castilla y León',
    'Tarragona': 'Cataluña',
    'Teruel': 'Aragón',
    'Toledo': 'Castilla-La Mancha',
    'Valencia': 'Comunidad Valenciana',
    'Valladolid': 'Castilla y León',
    'Vizcaya': 'País Vasco',
    'Zamora': 'Castilla y León',
    'Zaragoza': 'Aragón',
    'Ceuta': 'Ciudad Autónoma de Ceuta',
    'Melilla': 'Ciudad Autónoma de Melilla'
}